services:
  angular-webapp:
    build: .
    ports:
      - 4200:4200
    depends_on:
      - nodejsendpoint
  mongo:
    image: mongo
    restart: always
    volumes:
      - /mnt/data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
  nodejsendpoint:
    build: ./nodejsEndpoint/
    ports:
      - "3000:3000"
    depends_on:
      - mongo
